---
router_id: 10.0.0.3
loopback0: 10.0.0.3
trunk_interface: FastEthernet0/0
trunk_peer: "SW5-DC-DIST f1/0"
p2p_links:
  - {interface: FastEthernet1/0, ip: 10.255.0.10, mask: 255.255.255.252, peer: "R4-CORE f2/0", cost: 10}
  - {interface: FastEthernet1/1, ip: 10.255.0.14, mask: 255.255.255.252, peer: "R1-HQ f1/1 (backup)", cost: 100}

