---
router_id: 10.0.0.4
loopback0: 10.0.0.4
p2p_links:
  - {interface: FastEthernet1/0, ip: 10.255.0.1, mask: 255.255.255.252, peer: "R1-HQ f1/0", cost: 10}
  - {interface: FastEthernet1/1, ip: 10.255.0.5, mask: 255.255.255.252, peer: "R2-BR f1/0", cost: 10}
  - {interface: FastEthernet2/0, ip: 10.255.0.9, mask: 255.255.255.252, peer: "R3-DC f1/0", cost: 10}

